added 7 motivational quotes
avats-dev/motivate pull request #110
Opened 2020-10-07 12:32 UTC by keshari777

Check one of the below boxes as per your PR

- [:heavy_check_mark:  ] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #16 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ :heavy_check_mark: ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ :heavy_check_mark: ] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

2020-10-09 01:05 UTC, avats-dev commented on motivate/data/keshari777.json
> +      "quote": "It’s not what you do once in a while it’s what you do day in and day out that makes the difference",
Add a comma after while.

2020-10-09 01:05 UTC, avats-dev commented on motivate/data/keshari777.json
> +      "quote": "If you can’t make a mistake you can’t make anything",
Add a comma after `mistake`.

2020-10-09 01:06 UTC, avats-dev commented on motivate/data/keshari777.json
> +      "quote": "If opportunity doesn’t knock build a door",
Add a comma after `knock`.

2020-10-09 01:08 UTC, avats-dev requested changes
@keshari777, Update with requested changes. Thanks :+1:

2020-10-12 08:02 UTC, keshari777 commented on motivate/data/keshari777.json
> +      "quote": "It’s not what you do once in a while it’s what you do day in and day out that makes the difference",
updated

2020-10-12 08:04 UTC, keshari777 commented on motivate/data/keshari777.json
> +      "quote": "If you can’t make a mistake you can’t make anything",
updated

2020-10-12 08:05 UTC, keshari777 commented on motivate/data/keshari777.json
> +      "quote": "If you can’t make a mistake you can’t make anything",
updated

2020-10-12 08:05 UTC, keshari777 commented on motivate/data/keshari777.json
> +      "quote": "If opportunity doesn’t knock build a door",
updated

2020-10-12 08:24 UTC, avats-dev approved these changes

2020-10-12 08:25 UTC, merged