Create 188.json : Added some personal favourite quotes.
avats-dev/motivate pull request #14
Opened 2020-09-25 00:55 UTC by swapniljha001

Check one of the below boxes as per your PR

- [x] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [x] Fixes another issue #1  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

2020-09-26 22:15 UTC, avats-dev requested changes
Nice work @swapniljha001 :tada: and thanks for your contribution. 
As `188.json` have been merged recently, there are merge conflicts now. And as you've opened #13 also, can you merge these both files in `187.json` or alternatively you can create a new one `190.json` for this one. 
Thanks.

2020-09-30 18:58 UTC, swapniljha001 commented
@avats-dev I have changed the filename to `190.json` to resolve the conflict issues.

2020-09-30 22:32 UTC, avats-dev approved these changes

2020-09-30 22:33 UTC, merged

2020-10-01 02:50 UTC, swapniljha001 commented
Thanks, @avats-dev for accepting the PR 👍🏻