added 190.json with anime qoutes
avats-dev/motivate pull request #29
Opened 2020-09-30 19:48 UTC by scshiv29-dev

Check one of the below boxes as per your PR

- [yes ] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #00 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [yes ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ yes] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

2020-10-02 14:07 UTC, scshiv29-dev commented
@avats-dev  will you please check this pr?

2020-10-02 23:46 UTC, avats-dev requested changes
@scshiv29-dev Can you please rename your file as mentioned here https://github.com/avats-dev/motivate#contribution Thanks.

2020-10-03 04:12 UTC, avats-dev approved these changes

2020-10-03 04:12 UTC, avats-dev commented
Thanks for your contribution :tada:

2020-10-03 04:12 UTC, merged